vich_uploader:
  db_driver: orm
  mappings:
    posteo_images:
      uri_prefix: /images/posteos
      upload_destination: "%kernel.project_dir%/public/images/posteos"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
